# Generated by Django 2.1.7 on 2019-04-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareLife', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='access_text',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='amentity_text',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='interaction_text',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='space_text',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='transit_text',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
