# Generated by Django 2.1.7 on 2019-04-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareLife', '0002_auto_20190419_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sqft',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=6),
        ),
    ]
